name: Node.js Package

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      rabbitmq:
        image: rabbitmq:management
        ports:
          - 5672/tcp
        options: '--health-cmd "rabbitmqctl status" --health-interval 10s --health-timeout 10s --health-retries 6 --health-start-period 60s'

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - name: 'test package'
        run: npm test
        env:
          REMIT_URL: amqp://localhost:${{ job.services.rabbitmq.ports[5672] }}

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@jpwilliams'
      - name: 'publish to gpr'
        run: |
          npm publish --registry=https://npm.pkg.github.com/jpwilliams --scope=@jpwilliams
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
